name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build using docker-compose
        run: docker-compose -f ./docker-compose.yml up --build
      - name: Check build artifacts
        run: ls -R build/
